In [1]:
%load_ext autoreload
%autoreload 2
%cd '~/deepshape/deepshape'
figdir = '../figures/'

/home/jorgen/deepshape/deepshape


In [2]:
from layers import FourierLayer2D
from layers import batch_quadratic
from networks import ReparametrizationNetwork2D

In [3]:
import time
import torch
import torch.nn as nn
import numpy as np

In [5]:
F = FourierLayer2D(1, init_scale=1e-1)
X = torch.rand(4, 2)

Z, J = F(X)
print(J.min())
print(F.traceD)
print(F.detD)
batch_quadratic(F.traceD, F.detD)

tensor(0.6966, grad_fn=<MinBackward1>)
tensor([[ 0.1437],
        [-0.3321],
        [-0.1582],
        [ 0.5502]], grad_fn=<ViewBackward>)
tensor([[-0.0829],
        [ 0.0287],
        [-0.1426],
        [ 0.0195]], grad_fn=<ViewBackward>)


tensor([[4.4453],
        [1.0000],
        [2.1507],
        [1.0000]], grad_fn=<SWhereBackward>)

In [20]:
J.argmin()

tensor(828)

In [16]:
F = FourierLayer2D(2, init_scale=
                   .
                   1.)
X = torch.rand(1024, 2)

Z, J = F(X)
print(J.min())
print(F.traceD)
print(F.detD)

F.project(epsilonl=1e-5, epsilonq=1e-5, delta=1e-7)

Z, J = F(X)
print(J.min())

if J.min().item() <= 0.:
    print("WARNING: DET=",J.min().item())

tensor(-1177.3469, grad_fn=<MinBackward1>)
tensor([[ -8.0286],
        [-17.4013],
        [  1.2573],
        ...,
        [ 32.3680],
        [-14.2864],
        [-10.3486]], grad_fn=<ViewBackward>)
tensor([[ 278.3307],
        [  24.1764],
        [-146.0351],
        ...,
        [ 236.2072],
        [  47.8085],
        [ 292.4898]], grad_fn=<ViewBackward>)
tensor(1.0383e-05, grad_fn=<MinBackward1>)


In [7]:
import torch.optim as optim


In [7]:
F.parameters()

<generator object Module.parameters at 0x7f8b8c995ac0>

In [14]:
opt = optim.SGD(F.parameters(), lr=1e3)

for i in range(1000):
    F = FourierLayer2D(5, init_scale=5e-2)
    X = torch.rand(1024, 2)

    Z, J = F(X)
    opt.zero_grad()
    opt.step()
    F.project(epsilonl=1e-2, epsilonq=1e-2, delta=1e-6)

    Z, J = F(X)
    if J.min().item() <= 0.:
        print("WARNING: DET=",J.min().item())
    

In [19]:
F = FourierLayer2D(2, init_scale=1e-2)
X = torch.rand(1024, 2)

Z, J = F(X)
print(J.min())
print(F.traceD)
print(F.detD)

F.project(epsilonl=1e-5, epsilonq=1e-5, delta=1e-7)

Z, J = F(X)
print(J.min())

if J.min().item() <= 0.:
    print("WARNING: DET=",J.min().item())

tensor(0.6193, grad_fn=<MinBackward1>)
tensor([[ 0.1038],
        [ 0.2028],
        [ 0.0880],
        ...,
        [-0.2613],
        [ 0.0859],
        [-0.0081]], grad_fn=<ViewBackward>)
tensor([[ 0.0622],
        [-0.0469],
        [ 0.0034],
        ...,
        [ 0.0359],
        [-0.0434],
        [ 0.0057]], grad_fn=<ViewBackward>)


RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [13]:
print(F.detD)
torch.where(
    torch.abs(F.detD) < 1e-6,
    1.,
    0.,
)
            

tensor([[ 0.2295],
        [-0.0980],
        [-0.4241],
        ...,
        [-0.0281],
        [-0.1622],
        [ 0.1125]], grad_fn=<ViewBackward>)


tensor([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]])

In [14]:
from layers import batch_quadratic

In [16]:
batch_quadratic(F.traceD, F.detD)

tensor([[1.0000],
        [4.6210],
        [1.6246],
        ...,
        [6.6036],
        [2.1764],
        [1.0000]], grad_fn=<SWhereBackward>)

In [17]:
-1 / torch.minimum(F.traceD, -torch.ones_like(F.traceD))

tensor([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]], grad_fn=<MulBackward0>)

In [18]:
-1 / torch.minimum(F.traceD, -torch.ones_like(F.traceD))

tensor([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]], grad_fn=<MulBackward0>)